# Use an official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json /app

# Remove existing node_modules and lock files to avoid platform issues
RUN rm -rf node_modules package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory, excluding node_modules
COPY . /app

# Start the application in development mode
CMD ["npm", "run", "dev"]
